#################
### AUTOSTART ###
#################

exec-once = hyprctl dispatch workspace 21; hyprctl dispatch movecursor 1280 720; hyprctl dispatch workspace 11
exec-once = hyprpaper
exec-once = waybar
exec-once = USE_LAYER_SHELL=0 vicinae server
exec-once = streamcontroller -b --close-running
exec-once = sleep 3; noisetorch -i -s alsa_input.usb-CMEDIA_Q9-1-00.mono-fallback

exec-once = appimage-run /home/hagen/Documents/OpenRGB/OpenRGB.AppImage --server --profile ALL_OFF
exec-once = sleep 5; com.artemis_rgb.Artemis --minimized

exec-once = bash /home/hagen/scripts/midivol/run.sh
exec-once = bash /home/hagen/scripts/movecur/run.sh
exec-once = bash /home/hagen/scripts/soundboard/run.sh
exec-once = bash /home/hagen/scripts/update.sh
exec-once = cd /home/hagen/docker/webping/ && docker compose up -d

exec-once = systemctl --user start hyprpolkitagent

exec-once = steam -silent
exec-once = tidal-hifi
exec-once = sleep 5; eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)

exec-once = sleep 3; bluetoothctl connect 2C:BE:EB:4B:F9:90
exec-once = gpu-screen-recorder -w DP-3 -c mp4 -k h265 -s 2560x1440 -f 30 -a "default_output|app-inverse:Chromium|app-inverse:WEBRTC VoiceEngine|app-inverse:Zen" -a "app:WEBRTC VoiceEngine"  -a "app:Zen" -a "default_input" -q high -r 180 -o /home/hagen/Videos/Clips
