# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Monospace

general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 0

}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 8, linear
}

background {
    monitor = 
    color = rgba(0,0,0,1)
}