preload = /home/hagen/wallpapers/2024-04-27_14.35.02.png
preload = /home/hagen/wallpapers/2024-08-01_23.44.08.png

wallpaper = DP-3, /home/hagen/wallpapers/2024-04-27_14.35.02.png
wallpaper = DP-2, /home/hagen/wallpapers/2024-08-01_23.44.08.png