###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/


# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = SUPER, Q, exec, zen-beta
bind = SUPER, C, killactive,
bind = SUPER ALT, C, forcekillactive,
bind = SUPER, M, exec, bash ~/scripts/logout.sh
bind = SUPER, L, exec, hyprlock
bind = SUPER, E, exec, $fileManager
bind = SUPER, F, togglefloating,
bind = SUPER SHIFT, F, fullscreen

bind = SUPER, SUPER_L, exec, vicinae vicinae://toggle
bind = SUPER, V, exec, vicinae vicinae://extensions/vicinae/clipboard/history
bindn = , escape, exec, vicinae vicinae://close


bind = SUPER, R, exec, ghostty
# --background=000000 --keybind='escape=quit' --title=fexec



#bind = SUPER, P, pseudo, # dwindle
bind = SUPER, J, togglesplit, # dwindle


bind = SUPER, left, movewindow, l
bind = SUPER, right, movewindow, r
bind = SUPER, up, movewindow, u
bind = SUPER, down, movewindow, d


###################
### KEYBINDINGS ###
###################

bind = SUPER, dead_circumflex, workspace, 1
bind = SUPER, 1, workspace, 11
bind = SUPER, 2, workspace, 12
bind = SUPER, 3, workspace, 13

bind = ALT, 1, workspace, 21
bind = ALT, 2, workspace, 22
bind = ALT, 3, workspace, 23


# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 11
bind = SUPER SHIFT, 2, movetoworkspace, 12
bind = SUPER SHIFT, 3, movetoworkspace, 13

bind = ALT SHIFT, 1, movetoworkspace, 21
bind = ALT SHIFT, 2, movetoworkspace, 22
bind = ALT SHIFT, 3, movetoworkspace, 23


# Example special workspace (scratchpad)
#bind = SUPER, S, togglespecialworkspace, magic
#bind = SUPER SHIFT, S, movetoworkspace, special:magic


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-


#bind = SUPER , H, exec, code ~/.config/hypr/
#bind = SUPER , N, exec, code /etc/nixos/
bind = SUPER, N, exec, code /home/hagen/.local/share/quicklink/

#bind = SUPER, V, exec, ghostty --title=clipse --background=000000 -e clipse

#bind = SUPER SHIFT, S, exec, grim -g "$(slurp -d -c 00000000 -s 00000000 -b ffffff20 -B 000000ff -w 0)" - | wl-copy
bind = SUPER SHIFT, S, exec, grimblast --freeze copysave area ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%m-%s).png && hyprctl setcursor theme_mycur 24


bind = , F8, exec, killall -SIGUSR1 gpu-screen-recorder && hyprctl notify 5 3000 "rgb(00ff00)" "Clip captured" && ~/scripts/soundboard/soundboard.sh /sfx/video_speichern.mp3
bind = SHIFT, F8, exec, hyprctl notify 3 3000 "rgb(ff0000)" "Not captured" && ~/scripts/soundboard/soundboard.sh /sfx/video_speichern.mp3

#bind = ALT, Tab, workspace, previousbinds
bind = ALT, Tab, workspace, previous
#bind = ALT, Tab, cyclenext, visible hist

bind = SUPER CTRL SHIFT, B, forcerendererreload

bind = SUPER, O, exec, scrcpy --video-codec-options=color-range=1 --video-encoder=c2.qti.avc.encoder
bind = SUPER SHIFT, S, exec, hyprctl -j activewindow | jq -r '"windowrule = , class:^(\(.class))$, title:^(\(.title))$"' | wl-copy
bind = SUPER SHIFT, C, exec, hyprpicker -r -q -a