# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

source = ~/.config/hypr/windowrules-float.conf

layerrule = blur,waybar
layerrule = ignorezero,waybar

layerrule = blur,vicinae
layerrule = ignorealpha 0, vicinae

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:(.*)

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^()$,title:^()$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrule = float, class:^(com.mitchellh.ghostty)$
windowrule = size 1300 650, class:^(com.mitchellh.ghostty)$
windowrule = float, title:(Mission Center)

windowrule = stayfocused, class:(gay.vaskel.Soteria)$, title:^(Authorize)$
windowrule = dimaround, class:(gay.vaskel.Soteria)$, title:^(Authorize)$
windowrule = bordercolor rgba(ff7000ee) rgba(ff0000ee) 45deg, class:(gay.vaskel.Soteria)$, title:^(Authorize)$
windowrule = stayfocused, class:^()$, title:^(Hyprland Polkit Agent)$
windowrule = dimaround, class:^()$, title:^(Hyprland Polkit Agent)$
windowrule = bordercolor rgba(ff7000ee) rgba(ff0000ee) 45deg, class:^()$, title:^(Hyprland Polkit Agent)$

windowrule = opacity 0, class:^(steam_app_2379780)$, title:^(Lovely.*)$
windowrule = noblur, class:^(steam_app_2379780)$, title:^(Lovely.*)$
windowrule = nofocus, class:^(steam_app_2379780)$, title:^(Lovely.*)$

windowrule = opacity 0, title:^(.*EasyAntiCheat_EOS_Setup\.exe)$
windowrule = noblur, title:^(.*EasyAntiCheat_EOS_Setup\.exe)$
windowrule = nofocus, title:^(.*EasyAntiCheat_EOS_Setup\.exe)$
windowrule = noinitialfocus, title:^(.*EasyAntiCheat_EOS_Setup\.exe)$
windowrule = opacity 0, class:^(steam_app_2073850)$, title:^()$
windowrule = noblur, class:^(steam_app_2073850)$, title:^()$
windowrule = nofocus, class:^(steam_app_2073850)$, title:^()$
windowrule = noinitialfocus, class:^(steam_app_2073850)$, title:^()$

windowrule = size 1260 700, class:^(nemo)$
windowrule = size 1300 700, class:^(org.gnome.Nautilus)$


#windowrule = noinitialfocus, class:^(steam_app_.*)$
windowrule = fullscreenstate 2 2, class:^(steam_app_[^d].*)$

#windowrule = monitor DP-3, class:^(Badlion Minecraft Client.*)$

windowrule = fullscreenstate 2 2, class:^(Badlion Minecraft Client.*)$

windowrule = float, class:^(chrome-calendar.google.com.*)$
windowrule = size 600 400, class:^(chrome-calendar.google.com.*)$
windowrule = move 1310 -460, class:^(chrome-calendar.google.com.*)$

windowrule = float, title:^(Vicinae Launcher)$
windowrule = monitor DP-3, title:^(Vicinae Launcher)$
windowrule = stayfocused, title:^(Vicinae Launcher)$

windowrule = noinitialfocus, class:^(spotify)$
windowrule = noclosefor 86400000, class:^(spotify)$

######################
### Spawnverhalten ###
######################

windowrule = monitor DP-2, class:^(discord)$
windowrule = workspace 31, class:^(spotify)$
windowrule = workspace 1, class:^(steam_app_.*)$
windowrule = workspace 1, class:^(Minecraft.*)$