windowrule = float, class:^(steam)$, title:^(Friends List)$
windowrule = float, title:^(Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser)$
windowrule = float, title:^(Steam Settings)$, class:^(steam)$

windowrule = float, class:^(file-pdf-load)$, title:^(Load PDF Image)$
windowrule = float, class:^(JackboxUtility)$
windowrule = float, class:^(localsend_app)$, title:^(LocalSend)$
windowrule = float, class:^(Beeper)$
windowrule = float, class:^(com.nextcloud.desktopclient.nextcloud)$
windowrule = float, class:^(org.gnome.Calculator)$, title:^(Calculator)$
windowrule = float, class:^(com.core447.StreamController)$
windowrule = float, class:^(nemo)$
windowrule = float, class:^(org.gnome.Nautilus)$, title:^(Loading…)$
windowrule = float, class:^(org.gnome.FileRoller)$

windowrule = float, class:^(Microsoft.*)$
windowrule = float, class:^(RAIL.*)$
windowrule = float, class:^(⚙️ Windows Explorer)$
windowrule = float, class:^(com.chatterino.)$
